modLoader="javafml"
loaderVersion="[45,)"
license="Custom license"

[[mods]]
modId="add_more_paintings"
version="1.0.0"
displayName="Add More Paintings"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MACHENIKE, MCreator"

[[dependencies.add_more_paintings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




